### ISSUE TITLE
{field_options} not rendering in email notification

### ISSUE THREAD

**Issue by diversionarytactic** [airways/ProForm#1]
The 3 form fields I have using `{field_options}` are not rendering in the email notification.

It only shows the following for each: `{field_options} {/field_options}` in the email.

The fields actually show in the database show, but I’d love to get this notification rendering properly as well.

Thanks!
PS. EE 2.8.1 - PF 1.7.5

**Comment by diversionarytactic** [comment]
My bad - I was using the old email notification template example. Ugh...feeling dumb.

**Comment by airways** [comment]
Glad you got this to work! Are the old templates still visible somewhere or were you just using something from your own notes?

**Comment by diversionarytactic** [comment]
I traced back to another project that was using version 1.4 and I'm guessing I took the email notification template from that example. When I used an upgraded version on a different project that code still worked because I never used a select or something that needed to render field_options - (snowball effect begins).
